### ISSUE TITLE
Global filter names have typos when ending in "y"

### ISSUE THREAD

**Issue by DillonMorrison** [looker/app-event-ga360#42]
"All Propertys" is incorrect :)

![screen shot 2018-09-19 at 4 29 35 pm](https://user-images.githubusercontent.com/9888083/45787299-6b9e0800-bc29-11e8-9037-f07e9ff41ad6.png)

**Comment by lukelooker** [comment]
Will be resolve by AppHost's (https://github.com/looker/app-host/issues/466)

**Comment by lukelooker** [comment]
FYI - This fix was completed in the new UI and will be available to everyone using that.
