### ISSUE TITLE
peer comparison report seems broken

### ISSUE THREAD

**Issue by jdavidson** [looker/app-event-ga360#7]
<img width="1552" alt="screen shot 2018-08-22 at 12 32 35 pm" src="https://user-images.githubusercontent.com/475941/44486093-83bd4000-a607-11e8-94d8-99c1d345efd3.png">

**Comment by DillonMorrison** [comment]
Prob need to refactor a bit based on the new structure... I'll look into this today

**Comment by AnnaSerova** [comment]
working on this now

**Comment by AnnaSerova** [comment]
Fixed now
